# syntax=docker/dockerfile:1.6

FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
RUN apk add --no-cache python3 make g++ \
  && ln -sf python3 /usr/bin/python
COPY package.json bun.lock ./
COPY prisma ./prisma
RUN npm install

FROM deps AS builder
ARG DATABASE_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_URL_INTERNAL
ARG NEXT_PUBLIC_SERVER_URL
ARG NEXTAUTH_SECRET
ARG RESEND_API_KEY
ARG STRIPE_SECRET_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG PAYPAL_CLIENT_ID
ARG PAYPAL_APP_SECRET
ARG PAYMENT_METHODS
ARG DEFAULT_PAYMENT_METHOD
ENV DATABASE_URL=${DATABASE_URL}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL}
ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
ENV PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
ENV PAYPAL_APP_SECRET=${PAYPAL_APP_SECRET}
ENV PAYMENT_METHODS=${PAYMENT_METHODS}
ENV DEFAULT_PAYMENT_METHOD=${DEFAULT_PAYMENT_METHOD}
COPY . .
RUN npm run build

FROM base AS dev
ENV NODE_ENV=development
COPY --from=deps /app/node_modules ./node_modules
COPY . .
CMD ["npm", "run", "dev"]

FROM base AS runner
ARG DATABASE_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_URL_INTERNAL
ARG NEXT_PUBLIC_SERVER_URL
ARG NEXTAUTH_SECRET
ARG RESEND_API_KEY
ARG STRIPE_SECRET_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG PAYPAL_CLIENT_ID
ARG PAYPAL_APP_SECRET
ARG PAYMENT_METHODS
ARG DEFAULT_PAYMENT_METHOD
ENV NODE_ENV=production \
    PORT=3000 \
    DATABASE_URL=${DATABASE_URL} \
    NEXTAUTH_URL=${NEXTAUTH_URL} \
    NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL} \
    NEXTAUTH_SECRET=${NEXTAUTH_SECRET} \
    NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL} \
    RESEND_API_KEY=${RESEND_API_KEY} \
    STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY} \
    PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID} \
    PAYPAL_APP_SECRET=${PAYPAL_APP_SECRET} \
    PAYMENT_METHODS=${PAYMENT_METHODS} \
    DEFAULT_PAYMENT_METHOD=${DEFAULT_PAYMENT_METHOD}
COPY --from=builder /app ./
RUN addgroup -g 1001 nodejs \
  && adduser -S nextjs -u 1001
RUN mkdir -p /tmp/.next/cache/images \
  && chown -R nextjs:nodejs /tmp/.next
USER nextjs
ENV NEXT_CACHE_DIR=/tmp/.next/cache
CMD ["npm", "run", "start"]
